groups:
  - name: aevalo_alerts
    interval: 30s
    rules:
      # Backend health check
      - alert: BackendDown
        expr: up{job="backend"} == 0
        for: 1m
        annotations:
          summary: "Backend is down"
          description: "Backend service is not responding"

      # High response latency
      - alert: HighLatency
        expr: histogram_quantile(0.95, request_duration_seconds_bucket) > 1
        for: 5m
        annotations:
          summary: "High API latency detected"
          description: "95th percentile response time exceeds 1 second"

      # High error rate
      - alert: HighErrorRate
        expr: (rate(requests_total{status=~"5.."}[5m]) / rate(requests_total[5m])) > 0.05
        for: 5m
        annotations:
          summary: "High error rate detected"
          description: "Error rate exceeds 5%"

      # Database connection pool exhaustion
      - alert: DatabasePoolExhausted
        expr: db_connection_pool_current >= db_connection_pool_max * 0.9
        for: 5m
        annotations:
          summary: "Database connection pool nearly full"
          description: "Connection pool usage exceeds 90%"
